### ISSUE TITLE
Change default NGB behaviour in docker image  to access files on host machine without registering

### ISSUE THREAD

**Issue by GennadiyZakharov** [epam/NGB#24] opened 2017-07-31 09:40 UTC
I'm running NGB from docker container on laptop to work with my own data. So, I've mounted my data folder to docker as :/ngs  
But it looks complicated to register all files I want to view in NGB. In addition, running NGB cli inside docker container was tricky to me first time.
I suggest changing default behavior of NGB server in docker container  to access all data in mounted folder without registering.

**Comment by sidoruka** [comment] 2017-08-29 12:09
@GennadiyZakharov , could you please take a look in the latest `develop` branch? Now a folder, that is mounted using `-v :/ngs` is automatically available using `Open from NGB server` menu.
This is now described in [Using a demo version as a standalone viewer](https://github.com/epam/NGB/blob/develop/docs/md/installation/docker.md#using-a-demo-version-as-a-standalone-viewer)

Also `demo docker` now includes the following reference genomes together with genes:
- GRCh38
- GRCh37/hg19
- GRCm38/mm10
- dm6

To build it from a `develop` branch:
```bash
git clone https://github.com/epam/NGB.git -b develop
cd NGB
./gradlew buildDockerDemo
```

This will create two docker images:
```bash
REPOSITORY          TAG                 
ngb                 latest-demo    
ngb                 latest             
```

Then you can run `latest-demo` with a mounted folder:
```bash
MY_NGS_FOLDER=/path/to/ngs/data
docker run -d -p 8080:8080 -v $MY_NGS_FOLDER:/ngs ngb:latest-demo
```

And access NGB on http://localhost:8080/catgenome

Data from $MY_NGS_FOLDER will be available through `Open from NGB server` menu

**Comment by GennadiyZakharov** [comment] 2017-08-31 11:45
Several tests failed. Trying to build without tests
Here is part of the log:

:ngb:server:catgenome:test

com.epam.catgenome.manager.wig.BedGraphProcessorTest > saveBedGraphTest FAILED
    java.lang.NumberFormatException at BedGraphProcessorTest.java:123

com.epam.catgenome.manager.wig.BedGraphProcessorTest > saveBedGraphGzTest FAILED
    java.lang.NumberFormatException at BedGraphProcessorTest.java:160

com.epam.catgenome.manager.externaldb.NCBIGeneManagerTest > testGeneFetch FAILED
    com.epam.catgenome.exception.ExternalDbUnavailableException at NCBIGeneManagerTest.java:138
        Caused by: java.io.IOException at NCBIGeneManagerTest.java:138

251 tests completed, 3 failed, 16 skipped
:ngb:server:catgenome:test FAILED
:buildJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ngb:server:catgenome:test'.
> There were failing tests. See the report at: file:///home/gena/apps/ngb-develop/NGB/server/catgenome/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14 mins 27.281 secs

**Comment by GennadiyZakharov** [comment] 2017-08-31 12:24
How to build docker image without tests?
I've tried 
`./gradlew buildDockerDemo -x test`
and
`./gradlew buildDockerDemo -x server:catgenome:test`
with no effect

**Comment by sidoruka** [comment] 2017-08-31 12:34
You can do `./gradlew buildDockerDemo -PnoTest`

**Comment by sidoruka** [comment] 2017-09-08 09:13
@GennadiyZakharov , closing this for now, as current problems are coming from docker-service network configuration and not caused by NGB

Feel free to provide more feedback and I'll reopen the issue

**Closed by sidoruka** 2017-09-08 09:13 UTC
Labels: enhancement
