### ISSUE TITLE
NGB can't fetch information from UniProt 

### ISSUE THREAD

**Issue by Dmitrii-Romanov** [epam/NGB#283] opened 2019-04-12 08:08 UTC
Click on a gene, then "Show info", UNIPROT.
Following message appears:
**No Data Available
Unexpected HTTP status: 301 Moved Permanently for URL http://www.uniprot.org/uniprot/?query=ENSG00000229102&format=xml**

![image](https://user-images.githubusercontent.com/30798676/56021921-4a128400-5d13-11e9-8e06-d1acf2a7c462.png)

**Comment by sidoruka** [comment] 2021-02-12 12:35
Closing as a duplicate of #371

**Closed as completed by sidoruka** 2021-02-12 12:35 UTC
Labels: kind/bug, kind/duplicate
